import type { Metadata } from "next";
import { Faustina, Inter } from "next/font/google";
import "./globals.css";

const faustina = Faustina({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-faustina",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${faustina.variable} ${inter.variable}`}>
      <body>{children}</body>
    </html>
  );
}
